name: Build

on: [push]

jobs:
  build:
    name: Generate Thesis
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git Repository
        uses: actions/checkout@v2

      - name: Set up Enviroment
        run: |
          sudo apt install texlive texlive-xetex texlive-extra-utils texlive-lang-czechslovak texlive-bibtex-extra
          sudo apt install biber

          sudo timedatectl set-timezone Europe/Prague
          echo "RUN_TAG=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV
      - name: Run Arara -- Thesis
        run: arara thesis

      - name: Rename PDF
        run: mv thesis.pdf BP_Stepanek_Martin.pdf

      - name: Upload Data as Artifact
        uses: actions/upload-artifact@master
        with:
          name: BP_${{ env.RUN_TAG }}
          path: BP_Stepanek_Martin.pdf

      - name: Cat Log
        if: failure()
        run: |
          cat main.log
          ls -la